"""Add embedding provider and model fields to DocumentationCollection

Revision ID: 03a55a83680e
Revises: 53dc765afd92
Create Date: 2025-11-15 15:24:39.135925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03a55a83680e'
down_revision = '53dc765afd92'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns as nullable first to handle existing rows
    op.add_column('documentation_collections', sa.Column('embedding_provider', sa.String(), nullable=True))
    op.add_column('documentation_collections', sa.Column('embedding_model', sa.String(), nullable=True))

    # Set default values for existing rows (assume local embeddings for old collections)
    op.execute("UPDATE documentation_collections SET embedding_provider = 'local' WHERE embedding_provider IS NULL")
    op.execute("UPDATE documentation_collections SET embedding_model = 'BAAI/bge-small-en-v1.5' WHERE embedding_model IS NULL")

    # Now make columns non-nullable
    op.alter_column('documentation_collections', 'embedding_provider', nullable=False)
    op.alter_column('documentation_collections', 'embedding_model', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documentation_collections', 'embedding_model')
    op.drop_column('documentation_collections', 'embedding_provider')
    # ### end Alembic commands ###

