"""add_collection_sharing_and_visibility

Revision ID: ada6cce15156
Revises: 03a55a83680e
Create Date: 2025-11-15 19:07:02.449568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ada6cce15156'
down_revision = '03a55a83680e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create table - SQLAlchemy will create sharepermission enum automatically
    op.create_table('collection_shares',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('collection_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('permission', sa.Enum('VIEW', 'CHAT', name='sharepermission'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['documentation_collections.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', 'user_id', name='unique_collection_user_share')
    )

    # Create collectionvisibility enum before adding column
    collectionvisibility = sa.Enum('PRIVATE', 'PUBLIC', name='collectionvisibility')
    collectionvisibility.create(op.get_bind())

    op.add_column('documentation_collections', sa.Column('visibility', collectionvisibility, server_default='PRIVATE', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documentation_collections', 'visibility')
    op.drop_table('collection_shares')

    # Drop enum types
    sa.Enum(name='collectionvisibility').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='sharepermission').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###

